/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agendamedica;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.dao.MedicoDAO;
import model.dao.PacienteDAO;

/**
 *
 * @author super
 */
public class CadastrarPessoa extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPessoa
     */
    public CadastrarPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbxPaciente = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelCRM = new javax.swing.JLabel();
        cbxMedico = new javax.swing.JCheckBox();
        lblNome = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblConfirmarSenha = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEspecialidade = new javax.swing.JLabel();
        cpfTxt = new javax.swing.JTextField();
        nomeTxt = new javax.swing.JTextField();
        senhaTxt = new javax.swing.JTextField();
        confirmarTxt = new javax.swing.JTextField();
        especialidadeTxt = new javax.swing.JTextField();
        dataTxt = new javax.swing.JTextField();
        crmTxt = new javax.swing.JTextField();
        sexoTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRO");
        setMinimumSize(new java.awt.Dimension(816, 581));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 460, 72, 23);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 460, 76, 23);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("           JANELA DE CADASTRO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 0, 303, 40);

        cbxPaciente.setText("Paciente");
        cbxPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(cbxPaciente);
        cbxPaciente.setBounds(380, 60, 85, 20);

        jLabel2.setText("Qual sua situacao?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 60, 157, 16);

        jLabelCPF.setText("CPF:");
        getContentPane().add(jLabelCPF);
        jLabelCPF.setBounds(170, 370, 50, 16);

        jLabelCRM.setText("CRM:");
        getContentPane().add(jLabelCRM);
        jLabelCRM.setBounds(170, 330, 50, 16);

        cbxMedico.setText("Medico");
        cbxMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(cbxMedico);
        cbxMedico.setBounds(530, 60, 85, 20);

        lblNome.setText("Nome: ");
        getContentPane().add(lblNome);
        lblNome.setBounds(170, 130, 115, 16);

        lblData.setText("Data de nascimento:");
        getContentPane().add(lblData);
        lblData.setBounds(170, 280, 120, 16);

        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(170, 180, 113, 16);

        lblConfirmarSenha.setText("Confirmar senha:");
        getContentPane().add(lblConfirmarSenha);
        lblConfirmarSenha.setBounds(170, 230, 89, 16);

        lblSexo.setText("Sexo:");
        getContentPane().add(lblSexo);
        lblSexo.setBounds(170, 330, 89, 16);

        lblEspecialidade.setText("Especialidade:");
        getContentPane().add(lblEspecialidade);
        lblEspecialidade.setBounds(170, 280, 76, 16);

        cpfTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTxtActionPerformed(evt);
            }
        });
        getContentPane().add(cpfTxt);
        cpfTxt.setBounds(310, 360, 400, 30);
        getContentPane().add(nomeTxt);
        nomeTxt.setBounds(310, 130, 403, 22);
        getContentPane().add(senhaTxt);
        senhaTxt.setBounds(310, 172, 403, 30);
        getContentPane().add(confirmarTxt);
        confirmarTxt.setBounds(310, 222, 403, 30);
        getContentPane().add(especialidadeTxt);
        especialidadeTxt.setBounds(310, 270, 403, 30);

        dataTxt.setText("dd/mm/aa");
        dataTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTxtActionPerformed(evt);
            }
        });
        getContentPane().add(dataTxt);
        dataTxt.setBounds(310, 272, 403, 30);
        getContentPane().add(crmTxt);
        crmTxt.setBounds(310, 320, 400, 30);

        sexoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(sexoTxt);
        sexoTxt.setBounds(310, 312, 403, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/blackkk.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-4, -12, 870, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Cadastro frame = new Cadastro();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPacienteActionPerformed
        // TODO add your handling code here:
        if(cbxPaciente.isSelected()==true&&cbxMedico.isSelected()==false){
            lblData.setVisible(true);
            dataTxt.setVisible(true);
            lblSexo.setVisible(true);
            sexoTxt.setVisible(true);
            cpfTxt.setVisible(true);
            jLabelCPF.setVisible(true);
        }
        else{
            lblData.setVisible(false);
            dataTxt.setVisible(false);
            lblSexo.setVisible(false);
            sexoTxt.setVisible(false);
            cpfTxt.setVisible(false);
            jLabelCPF.setVisible(false);
            lblEspecialidade.setVisible(false);
            especialidadeTxt.setVisible(false);
            crmTxt.setVisible(false);
            jLabelCRM.setVisible(false);
        }
    }//GEN-LAST:event_cbxPacienteActionPerformed

    private void cbxMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMedicoActionPerformed
        // TODO add your handling code here:
        if(cbxMedico.isSelected()==true&&cbxPaciente.isSelected()==false){
            lblEspecialidade.setVisible(true);
            especialidadeTxt.setVisible(true);
            crmTxt.setVisible(true);
            jLabelCRM.setVisible(true);
        }
        else{
            lblEspecialidade.setVisible(false);
            especialidadeTxt.setVisible(false);
            crmTxt.setVisible(false);
            jLabelCRM.setVisible(false);
            lblData.setVisible(false);
            dataTxt.setVisible(false);
            lblSexo.setVisible(false);
            sexoTxt.setVisible(false);
            cpfTxt.setVisible(false);
            jLabelCPF.setVisible(false);
        }
    }//GEN-LAST:event_cbxMedicoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblEspecialidade.setVisible(false);
        especialidadeTxt.setVisible(false);
        lblData.setVisible(false);
        dataTxt.setVisible(false);
        lblSexo.setVisible(false);
        sexoTxt.setVisible(false);
        jLabelCRM.setVisible(false);
        jLabelCPF.setVisible(false);
        crmTxt.setVisible(false);
        cpfTxt.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PacienteDAO daop = new PacienteDAO();
        MedicoDAO daom = new MedicoDAO();
        //Caso cadastro paciente
        if(cbxPaciente.isSelected()==true && cbxMedico.isSelected()==false){
            String nome = nomeTxt.getText().toUpperCase();
            String senha = senhaTxt.getText();
            String confirmar = confirmarTxt.getText();
            String data_nascimento = dataTxt.getText();
            String sexo = sexoTxt.getText();
            String cpf = cpfTxt.getText();
            boolean verificador = false;
            if(daop.checkLogin(cpf, senha) == true){
                verificador=true;
                JOptionPane.showMessageDialog(null, "Usuário ja cadastrado");
            }
            String[] vetorData = data_nascimento.split("(?!^)");
            
            if(verificador==false&&senha.equals(confirmar)==true&&vetorData.length!=8){
                SimpleDateFormat formatoOriginal = new SimpleDateFormat("dd/MM/yy");
                SimpleDateFormat formatoDesejado = new SimpleDateFormat("yy/MM/dd");
                Date data;
                try {
                    // Parse a data original para um objeto Date
                    data = formatoOriginal.parse(data_nascimento);
                    // Formate a data para o formato desejado
                    String dataFormatada = formatoDesejado.format(data);
                    Paciente paciente = new Paciente(nome,dataFormatada,sexo,senha,cpf);
                    daop.create(paciente);
                } catch (ParseException ex) {
                    Logger.getLogger(CadastrarPessoa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Olá, datas inseridas inválidas");
            }
            if(senha.equals(confirmar)==false){
                JOptionPane.showMessageDialog(null, "Olá, o Cadastro não deu certo! senhas nao batem.","ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
        //Caso cadastro medico
        if(cbxPaciente.isSelected()==false&&cbxMedico.isSelected()==true){
            String nome = nomeTxt.getText().toUpperCase();
            String senha = senhaTxt.getText();
            String confirmar = confirmarTxt.getText();
            String especialidade = especialidadeTxt.getText().toUpperCase();
            String crm = crmTxt.getText();
            boolean verificador2=false;
            if(daom.checkLogin(crm, senha) == true){
                verificador2=true;
                JOptionPane.showMessageDialog(null," Usuário já cadastrado!");
                
            }
            
            if(verificador2==false&&senha.equals(confirmar)==true){
                Medico medico = new Medico(nome,especialidade,senha,crm);
                String senhaAdm = JOptionPane.showInputDialog("Para castrar um medico precisa-se da senha do admnistrador ");
                daom.create(medico, senhaAdm);
            }
            if(senha.equals(confirmar)==false){
                JOptionPane.showMessageDialog(null, "Olá, o Cadastro não deu certo! senhas nao batem.","ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
        //Caso a pessoa tenha deixado os dois cbx ligados
        if((cbxPaciente.isSelected()==true&&cbxMedico.isSelected()==true)||(cbxMedico.isSelected()==false&&cbxPaciente.isSelected()==false)){
            JOptionPane.showMessageDialog(null, "Olá, o Cadastro não deu certo! Voce deixou ambas opções ativas ou inativas.","ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dataTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataTxtActionPerformed

    private void cpfTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTxtActionPerformed

    private void sexoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxMedico;
    private javax.swing.JCheckBox cbxPaciente;
    private javax.swing.JTextField confirmarTxt;
    private javax.swing.JTextField cpfTxt;
    private javax.swing.JTextField crmTxt;
    private javax.swing.JTextField dataTxt;
    private javax.swing.JTextField especialidadeTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCRM;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEspecialidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JTextField senhaTxt;
    private javax.swing.JTextField sexoTxt;
    // End of variables declaration//GEN-END:variables
}
