/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agendamedica;

import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.ConsultaDAO;
import model.dao.PacienteDAO;

/**
 *
 * @author super
 */
public class RealizarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form RealizarConsulta
     */
    public RealizarConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsultas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        dataRelatorioTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblEscolha = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE REALIZAÇÃO DE CONSULTAS");
        setMinimumSize(new java.awt.Dimension(822, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jtConsultas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jtConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medico", "Paciente", "Data", "Horario", "id_consulta"
            }
        ));
        jtConsultas.getTableHeader().setResizingAllowed(false);
        jtConsultas.getTableHeader().setReorderingAllowed(false);
        jtConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtConsultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtConsultas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 160, 719, 381);

        jLabel1.setText("Digite a data atual (formato dd/mm/aaaa):");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 50, 280, 16);

        dataRelatorioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataRelatorioTxtActionPerformed(evt);
            }
        });
        getContentPane().add(dataRelatorioTxt);
        dataRelatorioTxt.setBounds(490, 50, 138, 22);

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 570, 80, 23);

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 570, 72, 23);

        lblEscolha.setText("Escolha uma consulta:");
        getContentPane().add(lblEscolha);
        lblEscolha.setBounds(210, 90, 230, 16);

        btnCancelar.setText("Sair");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(710, 570, 85, 23);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Sistema de realizacao de consultas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(256, 6, 350, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/blackkk.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 940, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataRelatorioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataRelatorioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataRelatorioTxtActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblEscolha.setVisible(false);
        Medico medico = Cadastro.getMedico();
        ArrayList<Consulta> consultas = medico.getConsultas();
        PacienteDAO daop = new PacienteDAO();
        SimpleDateFormat formatoOriginal = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat formatoDesejado = new SimpleDateFormat("dd-MM-yyyy");
        Date data;
        for(int i =0;i<consultas.size();i++){
            Consulta consulta = medico.getConsultaIndex(i);
            try {
                data = formatoOriginal.parse(consulta.getData());
                String dataFormatada = formatoDesejado.format(data);
                DefaultTableModel dtmConsultas = (DefaultTableModel) jtConsultas.getModel();
                Object[] dados = {medico.getNome(),daop.returnPaciente(consulta.getIdPaciente()).getNome(),dataFormatada,consulta.getHorario(),consulta.getId()};
                dtmConsultas.addRow(dados);
            } catch (ParseException ex) {
                Logger.getLogger(RealizarConsulta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        medico.resetConsultas();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dataRelatorio = dataRelatorioTxt.getText();
        String[] vetorData = dataRelatorio.split("(?!^)");
        SimpleDateFormat formatoOriginal = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat formatoDesejado = new SimpleDateFormat("yyyy-MM-dd");
        Date data;
        try {
            data = formatoOriginal.parse(dataRelatorio);
            String dataFormatada = formatoDesejado.format(data);
            PacienteDAO daop = new PacienteDAO();
        if(vetorData.length!=10){
            JOptionPane.showMessageDialog(null, "Olá, datas inseridas inválidas formato (dd-mm-yyyy). Nao esqueca de colocar o (-) ");
        }
        DefaultTableModel table = (DefaultTableModel) jtConsultas.getModel();
        int index5 = table.getRowCount();
        for(int x=0;x<index5;x++){
            table.removeRow(x);
        }
        lblEscolha.setVisible(true);
        Medico medico = Cadastro.getMedico();
        ArrayList<Consulta> consultas = medico.getConsultas();
        for(int i =0;i<consultas.size();i++){
            Consulta consulta = medico.getConsultaIndex(i);
            System.out.println(dataFormatada);
            System.out.println(consulta.getData());
            if(consulta.getData().equals(dataFormatada)){
                DefaultTableModel dtmConsultas = (DefaultTableModel) jtConsultas.getModel();
                Date dataMarcada = formatoOriginal.parse(consulta.getData());
                String dataConsulta = formatoDesejado.format(dataMarcada);
                Object[] dados = {medico.getNome(),daop.returnPaciente(consulta.getIdPaciente()).getNome(),dataConsulta,consulta.getHorario(),consulta.getId()};
                dtmConsultas.addRow(dados);
            }
        }
        medico.resetConsultas();
        } catch (ParseException ex) {
            Logger.getLogger(RealizarConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ConsultaDAO daoc = new ConsultaDAO();
        int row = jtConsultas.getSelectedRow();
        DefaultTableModel dtmConsultas = (DefaultTableModel) jtConsultas.getModel();
        String descricao = JOptionPane.showInputDialog("Insira a descrição da consulta:");
        String nomeMedico = (String) dtmConsultas.getValueAt(row, 0);
        String nomePaciente = (String) dtmConsultas.getValueAt(row,1);
        String data  = (String) dtmConsultas.getValueAt(row,2);
        String horario = (String) dtmConsultas.getValueAt(row, 3);
        int id = (Integer) dtmConsultas.getValueAt(row, 4);
        Consulta consultaRealizada = daoc.getConsultaId(id);
        consultaRealizada.setDescricao(descricao);
        consultaRealizada.setStatus("realizada");
        daoc.update(consultaRealizada);
        
        DefaultTableModel table = (DefaultTableModel) jtConsultas.getModel();
        int index5 = table.getRowCount();
        for(int x=0;x<index5;x++){
            System.out.println(x);
            table.removeRow(0);
        }
        JOptionPane.showMessageDialog(null, "Consulta realizada com sucesso");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtConsultasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtConsultasMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        PosLogin frame=new PosLogin();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField dataRelatorioTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtConsultas;
    private javax.swing.JLabel lblEscolha;
    // End of variables declaration//GEN-END:variables
}
